<?php
return [
	'list_form',
	'row'=>[
		'class'=>'text-center',
	],
	[
		'ListId',
		[
			'name'=>'name',
			'text'=>'姓名',
			'attr_style'=>'min-width:120px;',
		],
		'ListCustomerType',
		'ListPhone',
		'ListEmail',
		'ListCompanyName',
		'ListCustomerSource',
		'ListCountry',
		'ListSwitch',
		'ListCreateDate',
		'ListEditDelete',
	],
	'foot'=>'ListCustomerFoot',
];
